CREATE TABLE "Organizaciones" (
  "org_id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "nombre" text,
  "razon_social" text,
  "rfc" text,
  "cluni" text,
  "email" text,
  "contrasena" text,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "Donantes" (
  "donante_id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "org_id" uuid,
  "tipo_persona" text,
  "nombre_razon_social" text,
  "rfc" text,
  "curp" text,
  "regimen_fiscal" text,
  "codigo_postal" text,
  "direccion" text,
  "email" text,
  "actividad_economica" text,
  "es_pep" boolean DEFAULT false,
  "estatus_expediente" text,
  "donacion_acumulada" numeric DEFAULT 0,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "Donaciones" (
  "donacion_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "donante_id" uuid,
  "org_id" uuid,
  "monto" numeric,
  "fecha" timestamp with time zone DEFAULT now(),
  "metodo_pago" text,
  "valor_uma_aplicado" numeric,
  "requiere_reporte_pld" boolean DEFAULT false,
  "reportada_pld" boolean DEFAULT false,
  "fecha_reporte_pld" timestamp with time zone,
  "reportada_sat" boolean DEFAULT false,
  "uma_id" integer
);

CREATE TABLE "Gastos" (
  "gasto_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "org_id" uuid,
  "categoria" text,
  "concepto" text,
  "monto" numeric,
  "rfc_proveedor" text,
  "fecha" timestamp with time zone DEFAULT now()
);

CREATE TABLE "Documentos_Org" (
  "docs_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "org_id" uuid,
  "gasto_id" integer,
  "titulo" text,
  "tipo_archivo" text,
  "ruta_archivo" text,
  "numero_operacion_sat" text,
  "uuid_fiscal" text,
  "fecha_subida" timestamp with time zone DEFAULT now(),
  "fecha_vencimiento" timestamp with time zone
);

CREATE TABLE "Documentos_Donantes" (
  "docd_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "org_id" uuid,
  "donante_id" uuid,
  "donacion_id" integer,
  "tipo_documento" text,
  "ruta_archivo" text,
  "fecha_subida" timestamp with time zone DEFAULT now(),
  "fecha_vencimiento" timestamp with time zone
);

CREATE TABLE "Alertas_Cumplimiento" (
  "alerta_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "organizacion_id" uuid,
  "titulo" text,
  "mensaje" text,
  "tipo_alerta" text,
  "atendida" boolean DEFAULT false,
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE "Configuracion_UMA" (
  "uma_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "year" integer,
  "valor" numeric
);

COMMENT ON COLUMN "Documentos_Org"."gasto_id" IS 'Solo para documentos de gastos';

COMMENT ON COLUMN "Documentos_Org"."numero_operacion_sat" IS 'Solo para documentos que suben al sat';

COMMENT ON COLUMN "Documentos_Org"."uuid_fiscal" IS 'Solo para documentos de gastos';

COMMENT ON COLUMN "Documentos_Donantes"."donacion_id" IS 'Solo para donaciones';

ALTER TABLE "Donantes" ADD FOREIGN KEY ("org_id") REFERENCES "Organizaciones" ("org_id") ON DELETE CASCADE;

ALTER TABLE "Donaciones" ADD FOREIGN KEY ("donante_id") REFERENCES "Donantes" ("donante_id") ON DELETE CASCADE;

ALTER TABLE "Donaciones" ADD FOREIGN KEY ("org_id") REFERENCES "Organizaciones" ("org_id") ON DELETE CASCADE;

ALTER TABLE "Donaciones" ADD FOREIGN KEY ("uma_id") REFERENCES "Configuracion_UMA" ("uma_id") ON DELETE SET NULL;

ALTER TABLE "Gastos" ADD FOREIGN KEY ("org_id") REFERENCES "Organizaciones" ("org_id") ON DELETE CASCADE;

ALTER TABLE "Documentos_Org" ADD FOREIGN KEY ("org_id") REFERENCES "Organizaciones" ("org_id") ON DELETE CASCADE;

ALTER TABLE "Documentos_Donantes" ADD FOREIGN KEY ("org_id") REFERENCES "Organizaciones" ("org_id") ON DELETE CASCADE;

ALTER TABLE "Documentos_Donantes" ADD FOREIGN KEY ("donante_id") REFERENCES "Donantes" ("donante_id") ON DELETE CASCADE;

ALTER TABLE "Alertas_Cumplimiento" ADD FOREIGN KEY ("organizacion_id") REFERENCES "Organizaciones" ("org_id") ON DELETE CASCADE;

ALTER TABLE "Documentos_Org" ADD FOREIGN KEY ("gasto_id") REFERENCES "Gastos" ("gasto_id") ON DELETE CASCADE;

ALTER TABLE "Documentos_Donantes" ADD FOREIGN KEY ("donacion_id") REFERENCES "Donaciones" ("donacion_id") ON DELETE CASCADE;
