// Datos mock centralizados para todas las tablas del esquema
// Cada colección corresponde 1:1 con una tabla de la base de datos

import type {
    Organizacion,
    Donante,
    Donacion,
    Gasto,
    DocumentoOrg,
    DocumentoDonante,
    AlertaCumplimiento,
    ConfiguracionUMA,
} from "./types"

// ─── Configuración UMA ────────────────────────────────────────────────────────

export const mockUMA: ConfiguracionUMA[] = [
    { uma_id: 1, year: 2025, valor: 108.57 },
    { uma_id: 2, year: 2026, valor: 113.14 },
]

export const umaActual = mockUMA[1] // 2026

// ─── Organización ─────────────────────────────────────────────────────────────

export const mockOrganizacion: Organizacion = {
    org_id: "org-001",
    nombre: "Fundacion Esperanza A.C.",
    razon_social: "Fundacion Esperanza Asociacion Civil",
    rfc: "FES200301ABC",
    cluni: "FESE200301ABC123",
    email: "contacto@fundacionesperanza.org",
    created_at: "2020-03-01",
}

// ─── Donantes ──────────────────────────────────────────────────────────────────

export const mockDonantes: Donante[] = [
    {
        donante_id: "don-001",
        org_id: "org-001",
        tipo_persona: "moral",
        nombre_razon_social: "Inversiones del Norte S.A.",
        rfc: "INO850101AAA",
        regimen_fiscal: "601 - General de Ley Personas Morales",
        codigo_postal: "64000",
        direccion: "Av. Constitución 100, Monterrey, NL",
        email: "contacto@inversionesdelnorte.mx",
        actividad_economica: "Servicios financieros",
        es_pep: false,
        estatus_expediente: "completo",
        donacion_acumulada: 250000,
        created_at: "2025-12-15",
    },
    {
        donante_id: "don-002",
        org_id: "org-001",
        tipo_persona: "fisica",
        nombre_razon_social: "Carlos Mendez Rodriguez",
        rfc: "MERC890523BB1",
        curp: "MERC890523HNLNRL09",
        regimen_fiscal: "605 - Sueldos y Salarios",
        codigo_postal: "06600",
        direccion: "Calle Reforma 45, CDMX",
        email: "carlos.mendez@email.com",
        actividad_economica: "Empleado sector privado",
        es_pep: false,
        estatus_expediente: "completo",
        donacion_acumulada: 48500,
        created_at: "2025-12-18",
    },
    {
        donante_id: "don-003",
        org_id: "org-001",
        tipo_persona: "moral",
        nombre_razon_social: "Global Trading S.A. de C.V.",
        rfc: "GTS910301CC2",
        regimen_fiscal: "601 - General de Ley Personas Morales",
        codigo_postal: "11000",
        direccion: "Paseo de la Reforma 250, CDMX",
        email: "finanzas@globaltrading.mx",
        actividad_economica: "Comercio internacional",
        es_pep: false,
        estatus_expediente: "en_revision",
        donacion_acumulada: 980000,
        created_at: "2026-01-05",
    },
    {
        donante_id: "don-004",
        org_id: "org-001",
        tipo_persona: "fisica",
        nombre_razon_social: "Maria Fernanda Lopez",
        rfc: "LOFM920715DD3",
        curp: "LOFM920715MOCRPR05",
        regimen_fiscal: "612 - Personas Físicas con Actividades Empresariales",
        codigo_postal: "68000",
        direccion: "Calle Macedonio Alcalá 30, Oaxaca",
        email: "mflopez@gmail.com",
        actividad_economica: "Comercio al por menor",
        es_pep: false,
        estatus_expediente: "completo",
        donacion_acumulada: 15200,
        created_at: "2026-01-10",
    },
    {
        donante_id: "don-005",
        org_id: "org-001",
        tipo_persona: "moral",
        nombre_razon_social: "Tech Solutions Mexico",
        rfc: "TSM880920EE4",
        regimen_fiscal: "601 - General de Ley Personas Morales",
        codigo_postal: "44100",
        direccion: "Av. López Mateos 1500, Guadalajara, JAL",
        email: "donaciones@techsolutions.mx",
        actividad_economica: "Tecnología y software",
        es_pep: false,
        estatus_expediente: "completo",
        donacion_acumulada: 120000,
        created_at: "2026-01-22",
    },
    {
        donante_id: "don-006",
        org_id: "org-001",
        tipo_persona: "fisica",
        nombre_razon_social: "Roberto Sanchez Diaz",
        rfc: "SADR770412FF5",
        curp: "SADR770412HDFNCB02",
        regimen_fiscal: "605 - Sueldos y Salarios",
        codigo_postal: "83000",
        direccion: "Blvd. Rodolfo Elías Calles 120, Hermosillo, SON",
        email: "roberto.sanchez@email.com",
        actividad_economica: "Servidor público",
        es_pep: true,
        estatus_expediente: "en_revision",
        donacion_acumulada: 75000,
        created_at: "2026-02-01",
    },
    {
        donante_id: "don-007",
        org_id: "org-001",
        tipo_persona: "moral",
        nombre_razon_social: "Exportadora Pacific S.A.",
        rfc: "EPA960101GG6",
        regimen_fiscal: "601 - General de Ley Personas Morales",
        codigo_postal: "22000",
        direccion: "Blvd. Agua Caliente 4500, Tijuana, BC",
        email: "admin@exportadorapacific.mx",
        actividad_economica: "Exportación de mercancías",
        es_pep: false,
        estatus_expediente: "completo",
        donacion_acumulada: 430000,
        created_at: "2026-02-08",
    },
    {
        donante_id: "don-008",
        org_id: "org-001",
        tipo_persona: "fisica",
        nombre_razon_social: "Ana Gutierrez Vega",
        rfc: "GUVA850330HH7",
        curp: "GUVA850330MOCRNG09",
        regimen_fiscal: "612 - Personas Físicas con Actividades Empresariales",
        codigo_postal: "76000",
        direccion: "Calle Corregidora 88, Querétaro, QRO",
        email: "ana.gutierrez@gmail.com",
        actividad_economica: "Consultoría independiente",
        es_pep: false,
        estatus_expediente: "incompleto",
        donacion_acumulada: 22800,
        created_at: "2026-02-12",
    },
]

// ─── Donaciones ────────────────────────────────────────────────────────────────
// Umbral 2026: 645 UMAs = 645 × $113.14 = $72,975.30
// Si monto ≥ $72,975.30 → requiere_reporte_pld = true

export const mockDonaciones: (Donacion & { nombre_donante: string })[] = [
    {
        donacion_id: 1,
        donante_id: "don-001",
        org_id: "org-001",
        monto: 80000,
        fecha: "2026-01-15",
        metodo_pago: "transferencia",
        valor_uma_aplicado: 113.14,
        requiere_reporte_pld: true,
        reportada_pld: true,
        fecha_reporte_pld: "2026-01-20",
        reportada_sat: false,
        uma_id: 2,
        nombre_donante: "Inversiones del Norte S.A.",
    },
    {
        donacion_id: 2,
        donante_id: "don-001",
        org_id: "org-001",
        monto: 170000,
        fecha: "2026-02-01",
        metodo_pago: "transferencia",
        valor_uma_aplicado: 113.14,
        requiere_reporte_pld: true,
        reportada_pld: false,
        reportada_sat: false,
        uma_id: 2,
        nombre_donante: "Inversiones del Norte S.A.",
    },
    {
        donacion_id: 3,
        donante_id: "don-002",
        org_id: "org-001",
        monto: 12000,
        fecha: "2026-01-08",
        metodo_pago: "transferencia",
        valor_uma_aplicado: 113.14,
        requiere_reporte_pld: false,
        reportada_pld: false,
        reportada_sat: false,
        uma_id: 2,
        nombre_donante: "Carlos Mendez Rodriguez",
    },
    {
        donacion_id: 4,
        donante_id: "don-003",
        org_id: "org-001",
        monto: 350000,
        fecha: "2026-01-10",
        metodo_pago: "cheque",
        valor_uma_aplicado: 113.14,
        requiere_reporte_pld: true,
        reportada_pld: true,
        fecha_reporte_pld: "2026-01-18",
        reportada_sat: true,
        uma_id: 2,
        nombre_donante: "Global Trading S.A. de C.V.",
    },
    {
        donacion_id: 5,
        donante_id: "don-003",
        org_id: "org-001",
        monto: 630000,
        fecha: "2026-02-05",
        metodo_pago: "transferencia",
        valor_uma_aplicado: 113.14,
        requiere_reporte_pld: true,
        reportada_pld: false,
        reportada_sat: false,
        uma_id: 2,
        nombre_donante: "Global Trading S.A. de C.V.",
    },
    {
        donacion_id: 6,
        donante_id: "don-004",
        org_id: "org-001",
        monto: 8500,
        fecha: "2026-01-20",
        metodo_pago: "efectivo",
        valor_uma_aplicado: 113.14,
        requiere_reporte_pld: false,
        reportada_pld: false,
        reportada_sat: false,
        uma_id: 2,
        nombre_donante: "Maria Fernanda Lopez",
    },
    {
        donacion_id: 7,
        donante_id: "don-005",
        org_id: "org-001",
        monto: 120000,
        fecha: "2026-01-28",
        metodo_pago: "transferencia",
        valor_uma_aplicado: 113.14,
        requiere_reporte_pld: true,
        reportada_pld: true,
        fecha_reporte_pld: "2026-02-03",
        reportada_sat: true,
        uma_id: 2,
        nombre_donante: "Tech Solutions Mexico",
    },
    {
        donacion_id: 8,
        donante_id: "don-006",
        org_id: "org-001",
        monto: 75000,
        fecha: "2026-02-10",
        metodo_pago: "transferencia",
        valor_uma_aplicado: 113.14,
        requiere_reporte_pld: true,
        reportada_pld: false,
        reportada_sat: false,
        uma_id: 2,
        nombre_donante: "Roberto Sanchez Diaz",
    },
    {
        donacion_id: 9,
        donante_id: "don-007",
        org_id: "org-001",
        monto: 200000,
        fecha: "2026-02-14",
        metodo_pago: "cheque",
        valor_uma_aplicado: 113.14,
        requiere_reporte_pld: true,
        reportada_pld: false,
        reportada_sat: false,
        uma_id: 2,
        nombre_donante: "Exportadora Pacific S.A.",
    },
    {
        donacion_id: 10,
        donante_id: "don-008",
        org_id: "org-001",
        monto: 6700,
        fecha: "2026-02-18",
        metodo_pago: "transferencia",
        valor_uma_aplicado: 113.14,
        requiere_reporte_pld: false,
        reportada_pld: false,
        reportada_sat: false,
        uma_id: 2,
        nombre_donante: "Ana Gutierrez Vega",
    },
]

// ─── Gastos ────────────────────────────────────────────────────────────────────

export const mockGastos: Gasto[] = [
    {
        gasto_id: 1,
        org_id: "org-001",
        categoria: "Renta",
        concepto: "Renta de oficina — Enero 2026",
        monto: 18500,
        rfc_proveedor: "INMO800101XYZ",
        fecha: "2026-01-31",
    },
    {
        gasto_id: 2,
        org_id: "org-001",
        categoria: "Nómina",
        concepto: "Nómina personal operativo — Enero 2026",
        monto: 45000,
        rfc_proveedor: "FES200301ABC",
        fecha: "2026-01-31",
    },
    {
        gasto_id: 3,
        org_id: "org-001",
        categoria: "Servicios",
        concepto: "Servicio de internet y telefonía",
        monto: 3200,
        rfc_proveedor: "AMX870707JA0",
        fecha: "2026-01-05",
    },
    {
        gasto_id: 4,
        org_id: "org-001",
        categoria: "Materiales",
        concepto: "Material didáctico para talleres comunitarios",
        monto: 9800,
        rfc_proveedor: "OFF900601GHI",
        fecha: "2026-01-18",
    },
    {
        gasto_id: 5,
        org_id: "org-001",
        categoria: "Renta",
        concepto: "Renta de oficina — Febrero 2026",
        monto: 18500,
        rfc_proveedor: "INMO800101XYZ",
        fecha: "2026-02-28",
    },
    {
        gasto_id: 6,
        org_id: "org-001",
        categoria: "Viáticos",
        concepto: "Viáticos visita comunidades rurales — Equipo de campo",
        monto: 7400,
        rfc_proveedor: "FES200301ABC",
        fecha: "2026-02-10",
    },
    {
        gasto_id: 7,
        org_id: "org-001",
        categoria: "Servicios",
        concepto: "Auditoría externa anual — Despacho Contable González",
        monto: 22000,
        rfc_proveedor: "GOCA750312MNO",
        fecha: "2026-02-20",
    },
    {
        gasto_id: 8,
        org_id: "org-001",
        categoria: "Nómina",
        concepto: "Nómina personal operativo — Febrero 2026",
        monto: 45000,
        rfc_proveedor: "FES200301ABC",
        fecha: "2026-02-28",
    },
]

// ─── Documentos de la Organización ─────────────────────────────────────────────

export const mockDocumentosOrg: DocumentoOrg[] = [
    {
        docs_id: 1,
        org_id: "org-001",
        titulo: "Acta Constitutiva",
        tipo_archivo: "Legal",
        ruta_archivo: "/docs/acta.pdf",
        fecha_subida: "2025-12-15",
        fecha_vencimiento: "2030-12-15",
    },
    {
        docs_id: 2,
        org_id: "org-001",
        titulo: "Constancia de Situación Fiscal",
        tipo_archivo: "Fiscal",
        ruta_archivo: "/docs/csf.pdf",
        numero_operacion_sat: "OP-2025-001",
        fecha_subida: "2026-01-10",
        fecha_vencimiento: "2026-12-31",
    },
    {
        docs_id: 3,
        org_id: "org-001",
        gasto_id: 1,
        titulo: "Factura — Renta Enero 2026",
        tipo_archivo: "Gasto",
        ruta_archivo: "/docs/fac-001.pdf",
        uuid_fiscal: "UUID-2026-001",
        fecha_subida: "2026-01-31",
        fecha_vencimiento: "2027-01-31",
    },
    {
        docs_id: 4,
        org_id: "org-001",
        titulo: "CLUNI — Registro RFOSC",
        tipo_archivo: "Legal",
        ruta_archivo: "/docs/cluni.pdf",
        fecha_subida: "2020-03-01",
        fecha_vencimiento: "2027-03-01",
    },
    {
        docs_id: 5,
        org_id: "org-001",
        titulo: "Poder Notarial Representante",
        tipo_archivo: "Legal",
        ruta_archivo: "/docs/poder.pdf",
        fecha_subida: "2026-01-22",
        fecha_vencimiento: "2028-01-22",
    },
]

// ─── Documentos de Donantes ────────────────────────────────────────────────────

export const mockDocumentosDonantes: (DocumentoDonante & { nombre_donante: string })[] = [
    {
        docd_id: 1,
        org_id: "org-001",
        donante_id: "don-001",
        tipo_documento: "Identificación Oficial",
        ruta_archivo: "/docs/id-001.pdf",
        fecha_subida: "2025-12-15",
        fecha_vencimiento: "2027-05-01",
        nombre_donante: "Inversiones del Norte S.A.",
    },
    {
        docd_id: 2,
        org_id: "org-001",
        donante_id: "don-002",
        tipo_documento: "Comprobante de Domicilio",
        ruta_archivo: "/docs/dom-002.pdf",
        fecha_subida: "2025-12-18",
        fecha_vencimiento: "2026-03-18",
        nombre_donante: "Carlos Mendez Rodriguez",
    },
    {
        docd_id: 3,
        org_id: "org-001",
        donante_id: "don-003",
        donacion_id: 4,
        tipo_documento: "Constancia de Donación",
        ruta_archivo: "/docs/don-003.pdf",
        fecha_subida: "2026-01-05",
        fecha_vencimiento: "2027-01-05",
        nombre_donante: "Global Trading S.A. de C.V.",
    },
    {
        docd_id: 4,
        org_id: "org-001",
        donante_id: "don-006",
        tipo_documento: "Declaración de PEP",
        ruta_archivo: "/docs/pep-006.pdf",
        fecha_subida: "2026-02-01",
        fecha_vencimiento: "2027-02-01",
        nombre_donante: "Roberto Sanchez Diaz",
    },
    {
        docd_id: 5,
        org_id: "org-001",
        donante_id: "don-008",
        tipo_documento: "Identificación Oficial",
        ruta_archivo: "/docs/id-008.pdf",
        fecha_subida: "2026-02-12",
        fecha_vencimiento: "2026-04-12",
        nombre_donante: "Ana Gutierrez Vega",
    },
]

// ─── Alertas de Cumplimiento ───────────────────────────────────────────────────

export const mockAlertas: AlertaCumplimiento[] = [
    {
        alerta_id: 1,
        organizacion_id: "org-001",
        titulo: "Donación inusual detectada",
        mensaje: "Múltiples donaciones por montos que superan el umbral de 645 UMAs en un período de 48 horas. Se requiere reporte a la SHCP.",
        tipo_alerta: "donacion_inusual",
        atendida: false,
        created_at: "2026-02-18",
        donante_nombre: "Global Trading S.A.",
    },
    {
        alerta_id: 2,
        organizacion_id: "org-001",
        titulo: "Documento de expediente vencido",
        mensaje: "La identificación oficial presentada tiene una vigencia expirada. El expediente no puede marcarse como completo.",
        tipo_alerta: "documento_vencido",
        atendida: false,
        created_at: "2026-02-17",
        donante_nombre: "Roberto Sanchez Diaz",
    },
    {
        alerta_id: 3,
        organizacion_id: "org-001",
        titulo: "Donante clasificado como PEP",
        mensaje: "El donante presenta coincidencia con la lista de Personas Políticamente Expuestas. Se requiere diligencia debida reforzada.",
        tipo_alerta: "pep",
        atendida: false,
        created_at: "2026-02-16",
        donante_nombre: "Roberto Sanchez Diaz",
    },
    {
        alerta_id: 4,
        organizacion_id: "org-001",
        titulo: "Reporte PLD pendiente de envío",
        mensaje: "Existen 4 donaciones que superan el umbral de reporte y que aún no han sido reportadas al sistema PLD de la SHCP.",
        tipo_alerta: "reporte_pendiente",
        atendida: false,
        created_at: "2026-02-15",
    },
    {
        alerta_id: 5,
        organizacion_id: "org-001",
        titulo: "Expediente KYC incompleto",
        mensaje: "El expediente del donante no cuenta con comprobante de domicilio vigente ni constancia de situación fiscal.",
        tipo_alerta: "expediente_incompleto",
        atendida: true,
        created_at: "2026-02-14",
        donante_nombre: "Ana Gutierrez Vega",
    },
    {
        alerta_id: 6,
        organizacion_id: "org-001",
        titulo: "Donación inusual — patrón fraccionado",
        mensaje: "Se detectaron 8 donaciones consecutivas por montos justo debajo del umbral de reporte, sugiriendo posible fraccionamiento.",
        tipo_alerta: "donacion_inusual",
        atendida: true,
        created_at: "2026-02-13",
        donante_nombre: "Exportadora Pacific S.A.",
    },
]
